### PR TITLE
changes regarding the login page

### PR DESCRIPTION
**Pull request by Reda-Hammada**
**What does this PR do?**

This PR does the following:

- Adds a header navbar to the login form to give the user access to routes to other pages.
- Fixes the fixed navbar bug that was hiding the login form.
- Changes the login illustration to a more relevant one.
- Hides the illustration on mobile and tablet.

**Description of Task to be Completed?**    

 the PR includes screenshots of the changes made on large screens, landscape phones, and tablets. These screenshots provide visual confirmation of the changes made and help the reviewer to understand the impact of the changes on different devices.      

**How should this be manually tested?**   
 
- navigate to the login route    
- check the responsiveness  on different screens (mobile, laptop, tablet, large screens)     

**Any background context you want to provide?**

None   

**What are the relevant pivotal tracker/Trello stories?**
  
stories related to the authentication UI, especially the login component on the client side     

**Screenshots:**

### Large Screens
Large screens

### Landscape Phones
landscape phones

### Tablet
Tablet

### Phone     
Phone

### CODE REVIEW

**Comment by theChosenDevop** [comment]
Nice work. Love to see the changes implemented

**Comment by ALVINdimpos** [comment]
> adding Header navbar to the login form to give the user access to routes to other pages
> 
> fixing the fixed navbar bug hiding the login form
> 
> changing the login illustration to a more relevant one to log in
> 
> hiding the illustration on mobile and tablet
> 
> Screenshots :
> 
> Large screens
> 
> Large screens landscape phones landscape phones Tablet Tablet



> Nice work. Love to see the changes implemented

**Review by ALVINdimpos — COMMENTED** [review]
Great job! but one more thing. add screen shoot of mobile and for PR improvement use this template   
  
 ```
What does this PR do?
Description of Task to be completed?
How should this be manually tested?
Any background context you want to provide?
What are the relevant pivotal tracker/Trello stories?
Screenshots (if appropriate)
``` as a title. thank you

**Comment by Bowlu** [comment]
This is really nice, well done. But can you please include the PR questions Alvin sent before each answer, and also include a screenshot of the mobile view. Thank you Reda-Hammada.

**Comment by Reda-Hammada** [comment]
Thank you for your input, the changes have been made

**Pull request merged**
